USE [master]
GO

/****** Object:  Database [BeeService]    Script Date: 06-10-2015 21:28:16 ******/
CREATE DATABASE [BeeService]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BeeService', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BeeService.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BeeService_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BeeService_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BeeService] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BeeService].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BeeService] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BeeService] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BeeService] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BeeService] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BeeService] SET ARITHABORT OFF 
GO

ALTER DATABASE [BeeService] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BeeService] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BeeService] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BeeService] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BeeService] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BeeService] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BeeService] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BeeService] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BeeService] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BeeService] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BeeService] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BeeService] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BeeService] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BeeService] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BeeService] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BeeService] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BeeService] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BeeService] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BeeService] SET  MULTI_USER 
GO

ALTER DATABASE [BeeService] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BeeService] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BeeService] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BeeService] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BeeService] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BeeService] SET  READ_WRITE 
GO

