//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeCarService.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeeServiceEntities2 : DbContext
    {
        public BeeServiceEntities2()
            : base("name=BeeServiceEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddOn> AddOns { get; set; }
        public virtual DbSet<BeeUser> BeeUsers { get; set; }
        public virtual DbSet<Landmark> Landmarks { get; set; }
        public virtual DbSet<ServiceAddOn> ServiceAddOns { get; set; }
        public virtual DbSet<ServiceRequest> ServiceRequests { get; set; }
        public virtual DbSet<ServiceRequestVehicle> ServiceRequestVehicles { get; set; }
        public virtual DbSet<ServiceType> ServiceTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<VehicleClass> VehicleClasses { get; set; }
        public virtual DbSet<VehicleType> VehicleTypes { get; set; }
        public virtual DbSet<ServiceTeam> ServiceTeams { get; set; }
    }
}
