//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeCarService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceRequest()
        {
            this.ServiceRequestVehicles = new HashSet<ServiceRequestVehicle>();
        }
    
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime ServiceStartTime { get; set; }
        public Nullable<System.DateTime> ServiceEndTime { get; set; }
    
        public virtual BeeUser BeeUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestVehicle> ServiceRequestVehicles { get; set; }
    }
}
