//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeCarService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceType()
        {
            this.AddOns = new HashSet<AddOn>();
            this.ServiceRequestVehicles = new HashSet<ServiceRequestVehicle>();
        }
    
        public int ID { get; set; }
        public string ServiceType1 { get; set; }
        public int VehicleClassID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Duration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddOn> AddOns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestVehicle> ServiceRequestVehicles { get; set; }
        public virtual VehicleClass VehicleClass { get; set; }
    }
}
