//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeCarService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceAddOn
    {
        public int ID { get; set; }
        public int ServiceRequestVehicleID { get; set; }
        public Nullable<int> AddOnID { get; set; }
    
        public virtual AddOn AddOn { get; set; }
        public virtual ServiceRequestVehicle ServiceRequestVehicle { get; set; }
    }
}
